name: instant_doctor
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.2+3

environment:
  sdk: ">=2.19.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.2.2
  nb_utils: ^6.0.6
  smooth_page_indicator: ^1.1.0
  google_fonts: ^4.0.4
  keyboard_dismisser: ^3.0.0
  intl_phone_field: ^3.2.0
  sliding_up_panel: ^2.0.0+1
  intl:
  # flutter_stripe: ^9.5.0+1
  # agora_rtc_engine: ^6.2.6
  # permission_handler: ^11.0.1
  chat_bubbles: ^1.4.0
  dotted_border: ^2.1.0
  file_picker:
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.3
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  flutter_local_notifications: ^17.2.2
  google_sign_in: ^6.2.1
  timeago: ^3.3.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.4
  cached_network_image: ^3.2.3
  photo_view: ^0.15.0
  package_info_plus: ^8.0.2
  permission_handler:
  # flutter_incoming_call: ^0.1.2
  share_plus: ^10.1.0
  url_launcher: ^6.2.4
  tutorial_coach_mark: ^1.2.11
  dropdown_button2: ^2.3.9
  flutter_slidable: ^3.0.1
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.2
  in_app_review: ^2.0.8
  zego_uikit_prebuilt_call: ^4.16.12
  zego_uikit_signaling_plugin: ^2.8.6
  ionicons: ^0.2.2
  uuid: ^4.4.2
  accordion: ^2.6.0
  # time_picker_spinner_pop_up: ^2.0.0
  # board_datetime_picker: 2.1.5
  easy_date_timeline: ^1.1.3
  flutterwave_standard_smart: ^1.0.4
  sign_in_with_apple: ^6.1.3
  animated_bottom_navigation_bar: ^1.3.3
  flutter_staggered_grid_view: ^0.7.0
  # dependency_overrides:
  #   stripe_android: "9.5.0+1"

  http: any
  path: any
  audio_waveforms: ^1.1.1
  upgrader: ^11.3.0
  encrypt: ^5.0.3
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  flutter_typeahead: ^5.2.0
  flutter_widget_from_html: ^0.15.2
  animated_text_kit: ^4.2.2
  app_links: ^6.3.2
  paystack_for_flutter: ^1.0.2
  flutter_tawkto: ^0.0.4
  
  timezone: any
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  change_app_package_name:
  flutter_launcher_icons: ^0.14.1
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dependency_overrides:
  flutter_inappwebview_ios:
    git:
      url: https://github.com/andychucs/flutter_inAppWebview.git
      ref: master
      path: flutter_inappwebview_ios

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/audio/
    - assets/googlemap/map_style_dark.json
    - assets/googlemap/map_style_light.json
    - shorebird.yaml
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
