// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBABnO_FKoHf6spc7H46AzVLi__0fDAx8g',
    appId: '1:127248616649:web:7a9a63d31274ce79651118',
    messagingSenderId: '127248616649',
    projectId: 'instant-doctor-a4e4c',
    authDomain: 'instant-doctor-a4e4c.firebaseapp.com',
    storageBucket: 'instant-doctor-a4e4c.appspot.com',
    measurementId: 'G-8STYCQ8RPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMGvffD_GkXSpeW4MpLnol_xuiQ_6oAmU',
    appId: '1:127248616649:android:378d4a79ea84f105651118',
    messagingSenderId: '127248616649',
    projectId: 'instant-doctor-a4e4c',
    storageBucket: 'instant-doctor-a4e4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKjkgCSIZgzb0B4sogyIYoX9EJGkejY8U',
    appId: '1:127248616649:ios:85d223b22093a77c651118',
    messagingSenderId: '127248616649',
    projectId: 'instant-doctor-a4e4c',
    storageBucket: 'instant-doctor-a4e4c.appspot.com',
    iosBundleId: 'com.example.instantDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKjkgCSIZgzb0B4sogyIYoX9EJGkejY8U',
    appId: '1:127248616649:ios:85d223b22093a77c651118',
    messagingSenderId: '127248616649',
    projectId: 'instant-doctor-a4e4c',
    storageBucket: 'instant-doctor-a4e4c.appspot.com',
    iosBundleId: 'com.example.instantDoctor',
  );
}